//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_tsEntities : DbContext
    {
        public bd_tsEntities()
            : base("name=bd_tsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fact_especializa> fact_especializa { get; set; }
        public virtual DbSet<fact_est_exp> fact_est_exp { get; set; }
        public virtual DbSet<fact_est_mat> fact_est_mat { get; set; }
        public virtual DbSet<fact_estatus> fact_estatus { get; set; }
        public virtual DbSet<fact_estatus_material> fact_estatus_material { get; set; }
        public virtual DbSet<fact_estatus_qa> fact_estatus_qa { get; set; }
        public virtual DbSet<fact_tipo_err> fact_tipo_err { get; set; }
        public virtual DbSet<fact_tipo_rfc> fact_tipo_rfc { get; set; }
        public virtual DbSet<fact_tipo_usuarios> fact_tipo_usuarios { get; set; }
        public virtual DbSet<inf_caducidad_videos> inf_caducidad_videos { get; set; }
        public virtual DbSet<inf_caducidad_videos_dep> inf_caducidad_videos_dep { get; set; }
        public virtual DbSet<inf_dispositivos> inf_dispositivos { get; set; }
        public virtual DbSet<inf_dispositivos_dep> inf_dispositivos_dep { get; set; }
        public virtual DbSet<inf_empresa> inf_empresa { get; set; }
        public virtual DbSet<inf_exp_mat> inf_exp_mat { get; set; }
        public virtual DbSet<inf_fecha_transformacion> inf_fecha_transformacion { get; set; }
        public virtual DbSet<inf_fecha_transformacion_dep> inf_fecha_transformacion_dep { get; set; }
        public virtual DbSet<inf_juzgados> inf_juzgados { get; set; }
        public virtual DbSet<inf_juzgados_dep> inf_juzgados_dep { get; set; }
        public virtual DbSet<inf_log_ruta> inf_log_ruta { get; set; }
        public virtual DbSet<inf_master_jvl> inf_master_jvl { get; set; }
        public virtual DbSet<inf_material> inf_material { get; set; }
        public virtual DbSet<inf_material_dep> inf_material_dep { get; set; }
        public virtual DbSet<inf_material_ext> inf_material_ext { get; set; }
        public virtual DbSet<inf_material_ext_dep> inf_material_ext_dep { get; set; }
        public virtual DbSet<inf_ruta_videos> inf_ruta_videos { get; set; }
        public virtual DbSet<inf_ruta_videos_dep> inf_ruta_videos_dep { get; set; }
        public virtual DbSet<inf_salas> inf_salas { get; set; }
        public virtual DbSet<inf_salas_dep> inf_salas_dep { get; set; }
        public virtual DbSet<inf_sepomex> inf_sepomex { get; set; }
        public virtual DbSet<inf_tribunal> inf_tribunal { get; set; }
        public virtual DbSet<inf_tribunal_dep> inf_tribunal_dep { get; set; }
        public virtual DbSet<inf_usuarios> inf_usuarios { get; set; }
        public virtual DbSet<inf_usuarios_dep> inf_usuarios_dep { get; set; }
        public virtual DbSet<v_salas> v_salas { get; set; }
    }
}
