//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_material_ext_dep
    {
        public int id__material_ext_dep { get; set; }
        public string sesion { get; set; }
        public string video { get; set; }
        public int id_material { get; set; }
        public System.Guid id_usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_registro_alt { get; set; }
        public int id_material_ext { get; set; }
    }
}
