//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_fecha_transformacion
    {
        public int id_fecha_transformacion { get; set; }
        public Nullable<System.DateTime> horario { get; set; }
        public System.Guid id_usuario { get; set; }
        public System.Guid id_tribunal { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
