//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_salas
    {
        public System.Guid id_sala { get; set; }
        public int codigo_sala { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public string nombre { get; set; }
        public System.Guid id_juzgado { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
