//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_master_jvl
    {
        public System.Guid id_control_exp { get; set; }
        public string sesion { get; set; }
        public string titulo { get; set; }
        public string err_carga { get; set; }
        public Nullable<int> id_estatus_exp { get; set; }
        public Nullable<int> id_estatus_qa { get; set; }
        public Nullable<int> id_ruta_videos { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
