//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_exp_mat
    {
        public System.Guid id_exp_mat { get; set; }
        public string ruta_archivo { get; set; }
        public string ruta_ext { get; set; }
        public string duracion { get; set; }
        public string nom_archivo { get; set; }
        public int id_est_mat { get; set; }
        public Nullable<System.Guid> id_control_exp { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
