//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_usuarios_dep
    {
        public int id_usuario_dep { get; set; }
        public Nullable<System.Guid> id_usuario { get; set; }
        public Nullable<int> id_tipo_accion { get; set; }
        public Nullable<System.Guid> id_usuario_alt { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    }
}
