//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_material_ext
    {
        public int id_material_ext { get; set; }
        public string sesion { get; set; }
        public string archivo { get; set; }
        public string duracion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_estatus_material { get; set; }
        public Nullable<int> id_estatus_qa { get; set; }
        public Nullable<int> id_ruta_videos { get; set; }
        public int id_material { get; set; }
        public Nullable<System.Guid> id_control { get; set; }
    }
}
