//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_log_ruta
    {
        public int id_log_ruta { get; set; }
        public int id_ruta_videos { get; set; }
        public Nullable<int> id_tipo_err { get; set; }
        public string desc_error { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.Guid> id_control { get; set; }
    }
}
