//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_tsc
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_salas
    {
        public int codigo_juzgado { get; set; }
        public string desc_especializa { get; set; }
        public string localidad { get; set; }
        public string numero { get; set; }
        public Nullable<int> codigo_sala { get; set; }
        public string nombre { get; set; }
        public string ip { get; set; }
        public string usuario { get; set; }
        public string desc_ruta_ini { get; set; }
        public string ruta_user_ini { get; set; }
        public System.Guid id_juzgado { get; set; }
    }
}
